joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 0.00
    coalesce_interval: 0.001 # merging messeges in this interval

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.4
    scale_angular_turbo:
      yaw: 3.0


    enable_button: 2
    enable_turbo_button: 5

    require_enable_button: false